### ISSUE TITLE
data_overview.html todo list

### ISSUE THREAD

**Issue by Illustratien** [tillrose/BRIWECS_Data_Publication#25]
Wishlists of Readme #12 now migrated to data_overview.qmd for more extentions
and will be access in 
https://tillrose.github.io/BRIWECS_Data_Publication/data_overview.html

Here are the current reminder for improvements
  ### Exp design
  - [x] fix color names for each managements

  ### Pie overview
  - [x] remove figure margin or scale display text size
  ### corr plot
  - [x] x axis text angle to 45 degree
  ###  previous publication sections 
- [x] isolate from highlights tabs and add the hyperlinks of published datasets there
